"""Build a small static results page (GitHub Pages) from results/*.json. No dependencies."""
from __future__ import annotations
import html
import json
from pathlib import Path

from .evaluate import COLS

CSS = """:root{--bg:#fff;--ink:#1f2937;--mut:#6b7280;--line:#e5e7eb;--ok:#047857;--bad:#b91c1c;--soft:#f8fafc}
@media (prefers-color-scheme:dark){:root{--bg:#0f172a;--ink:#e5e7eb;--mut:#9ca3af;--line:#374151;--ok:#34d399;--bad:#f87171;--soft:#111827}}
body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 -apple-system,Segoe UI,Roboto,sans-serif}
main{max-width:980px;margin:0 auto;padding:24px 16px 64px}h1{font-size:1.6rem}h2{font-size:1.15rem;margin-top:2em}
table{border-collapse:collapse;width:100%;font-size:14px;display:block;overflow-x:auto}th,td{border:1px solid var(--line);padding:6px 10px;text-align:left}
th{background:var(--soft)}.ok{color:var(--ok);font-weight:600}.bad{color:var(--bad);font-weight:600}.mut{color:var(--mut);font-size:14px}"""


def build_site(results_dir: Path, out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    parts = []
    for f in sorted(results_dir.glob("p*.json")):
        r = json.loads(f.read_text())
        cols = r.get("columns") or COLS
        cls, label = ("ok", "PASS") if r["passed"] else ("bad", "FAIL")
        parts.append(f"<h2>{html.escape(r['title'])} <span class='{cls}'>{label}</span></h2><p class='mut'>{html.escape(r.get('notes', ''))}</p>")
        head = "".join(f"<th>{html.escape(c[1])}</th>" for c in cols)
        body = ""
        for name, m in r["configs"].items():
            b = " style='font-weight:700'" if name == r["main"] else ""
            body += f"<tr{b}><td>{html.escape(name)}</td>" + "".join(f"<td>{html.escape(str(m.get(c[0], '-')))}</td>" for c in cols) + "</tr>"
        parts.append(f"<table><tr><th>Config</th>{head}</tr>{body}</table>")
        if r["failed"]:
            parts.append(f"<p class='bad'>Failed: {html.escape('; '.join(r['failed']))}</p>")
    page = (f"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
            f"<title>RAG capstone results</title><style>{CSS}</style></head><body><main><h1>RAG capstone starters: evaluation results</h1>"
            f"<p class='mut'>Generated by CI. Offline defaults (hashing embedder, lexical reranker, extractive answers). Faithful* is a lexical proxy, not an LLM judge. "
            f"Small synthetic corpora give optimistic numbers.</p>{''.join(parts)}</main></body></html>")
    (out_dir / "index.html").write_text(page, encoding="utf-8")
    return out_dir / "index.html"
